"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FieldsTypes = void 0;
var FieldsTypes;
(function (FieldsTypes) {
    FieldsTypes["string"] = "string";
    FieldsTypes["password"] = "password";
    FieldsTypes["date"] = "date";
    FieldsTypes["datetime"] = "datetime";
    FieldsTypes["time"] = "time";
    FieldsTypes["integer"] = "integer";
    FieldsTypes["number"] = "number";
    FieldsTypes["float"] = "float";
    FieldsTypes["color"] = "color";
    FieldsTypes["email"] = "email";
    FieldsTypes["month"] = "month";
    FieldsTypes["week"] = "week";
    FieldsTypes["range"] = "range";
    FieldsTypes["boolean"] = "boolean";
    FieldsTypes["binary"] = "binary";
    FieldsTypes["text"] = "text";
    FieldsTypes["longtext"] = "longtext";
    FieldsTypes["mediumtext"] = "mediumtext";
    FieldsTypes["ckeditor"] = "ckeditor";
    FieldsTypes["wysiwyg"] = "wysiwyg";
    FieldsTypes["texteditor"] = "texteditor";
    FieldsTypes["word"] = "word";
    FieldsTypes["jsoneditor"] = "jsoneditor";
    FieldsTypes["json"] = "json";
    FieldsTypes["array"] = "array";
    FieldsTypes["object"] = "object";
    FieldsTypes["ace"] = "ace";
    FieldsTypes["html"] = "html";
    FieldsTypes["xml"] = "xml";
    FieldsTypes["aceeditor"] = "aceeditor";
    FieldsTypes["image"] = "image";
    FieldsTypes["images"] = "images";
    FieldsTypes["file"] = "file";
    FieldsTypes["files"] = "files";
    FieldsTypes["menu"] = "menu";
    FieldsTypes["navigation"] = "navigation";
    FieldsTypes["schedule"] = "schedule";
    FieldsTypes["worktime"] = "worktime";
    FieldsTypes["association"] = "association";
    FieldsTypes["association-many"] = "association-many";
})(FieldsTypes = exports.FieldsTypes || (exports.FieldsTypes = {}));
